/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cobacobi;

import cobacobi.*;

/**
 *
 * @author alfathrev
 */
public class Sidebar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Sidebar.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Sidebar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        SidebarPanel = new javax.swing.JPanel();
        BagianAtas = new javax.swing.JPanel();
        LogoFont = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnKaryawan = new javax.swing.JButton();
        btnKamar = new javax.swing.JButton();
        btnDaftar = new javax.swing.JButton();
        btnSetting = new javax.swing.JButton();
        BagianBawah = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CenterPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SidebarPanel.setBackground(new java.awt.Color(26, 26, 26));
        SidebarPanel.setPreferredSize(new java.awt.Dimension(264, 1024));
        SidebarPanel.setLayout(new java.awt.GridBagLayout());

        BagianAtas.setBackground(new java.awt.Color(26, 26, 26));
        BagianAtas.setPreferredSize(new java.awt.Dimension(264, 650));
        BagianAtas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoFont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/looghotel 1.png"))); // NOI18N
        BagianAtas.add(LogoFont, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, -1));

        btnHome.setBackground(new java.awt.Color(26, 26, 26));
        btnHome.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHome.setPreferredSize(new java.awt.Dimension(200, 27));
        btnHome.addActionListener(this::btnHomeActionPerformed);
        BagianAtas.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 130, -1));

        btnKaryawan.setBackground(new java.awt.Color(26, 26, 26));
        btnKaryawan.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        btnKaryawan.setText("Manajemen Karyawan");
        btnKaryawan.setBorderPainted(false);
        btnKaryawan.setContentAreaFilled(false);
        btnKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKaryawan.addActionListener(this::btnKaryawanActionPerformed);
        BagianAtas.add(btnKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        btnKamar.setBackground(new java.awt.Color(26, 26, 26));
        btnKamar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnKamar.setForeground(new java.awt.Color(255, 255, 255));
        btnKamar.setText("Manajemen Kamar");
        btnKamar.setBorderPainted(false);
        btnKamar.setContentAreaFilled(false);
        btnKamar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKamar.addActionListener(this::btnKamarActionPerformed);
        BagianAtas.add(btnKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        btnDaftar.setBackground(new java.awt.Color(26, 26, 26));
        btnDaftar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnDaftar.setForeground(new java.awt.Color(255, 255, 255));
        btnDaftar.setText("Daftar Kamar");
        btnDaftar.setBorderPainted(false);
        btnDaftar.setContentAreaFilled(false);
        btnDaftar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDaftar.addActionListener(this::btnDaftarActionPerformed);
        BagianAtas.add(btnDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        btnSetting.setBackground(new java.awt.Color(26, 26, 26));
        btnSetting.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnSetting.setForeground(new java.awt.Color(255, 255, 255));
        btnSetting.setText("Setting");
        btnSetting.setBorderPainted(false);
        btnSetting.setContentAreaFilled(false);
        btnSetting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSetting.addActionListener(this::btnSettingActionPerformed);
        BagianAtas.add(btnSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        SidebarPanel.add(BagianAtas, new java.awt.GridBagConstraints());

        BagianBawah.setBackground(new java.awt.Color(26, 26, 26));
        BagianBawah.setPreferredSize(new java.awt.Dimension(264, 374));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/BagianBawah.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(264, 594));

        javax.swing.GroupLayout BagianBawahLayout = new javax.swing.GroupLayout(BagianBawah);
        BagianBawah.setLayout(BagianBawahLayout);
        BagianBawahLayout.setHorizontalGroup(
            BagianBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BagianBawahLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BagianBawahLayout.setVerticalGroup(
            BagianBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BagianBawahLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        SidebarPanel.add(BagianBawah, gridBagConstraints);

        getContentPane().add(SidebarPanel, java.awt.BorderLayout.LINE_START);

        CenterPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Home");

        jButton1.setBackground(new java.awt.Color(194, 148, 233));
        jButton1.setBorderPainted(false);
        jButton1.setPreferredSize(new java.awt.Dimension(44, 44));
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("Cari...");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.setPreferredSize(new java.awt.Dimension(480, 44));

        jLabel3.setText("jLabel3");
        jLabel3.setPreferredSize(new java.awt.Dimension(1094, 352));

        javax.swing.GroupLayout CenterPanelLayout = new javax.swing.GroupLayout(CenterPanel);
        CenterPanel.setLayout(CenterPanelLayout);
        CenterPanelLayout.setHorizontalGroup(
            CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CenterPanelLayout.createSequentialGroup()
                .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CenterPanelLayout.createSequentialGroup()
                        .addContainerGap(58, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CenterPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        CenterPanelLayout.setVerticalGroup(
            CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CenterPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(CenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(582, Short.MAX_VALUE))
        );

        getContentPane().add(CenterPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKamarActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void btnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKaryawanActionPerformed

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSettingActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Sidebar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BagianAtas;
    private javax.swing.JPanel BagianBawah;
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JLabel LogoFont;
    private javax.swing.JPanel SidebarPanel;
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnKamar;
    private javax.swing.JButton btnKaryawan;
    private javax.swing.JButton btnSetting;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
