package com.mycompany.transylvaniahotel.gui;

/**
 *
 * @author alfathrev
 */
import com.mycompany.transylvaniahotel.dao.BaseDAO;
import com.mycompany.transylvaniahotel.dao.GenericDAO;
import com.mycompany.transylvaniahotel.model.Karyawan;

public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    public Login() {
        initComponents();

        jPasswordField1.setText("");

        this.setLocationRelativeTo(null);

        this.getContentPane().setLayout(new java.awt.LayoutManager() {

            @Override
            public void addLayoutComponent(String name, java.awt.Component comp) {
            }

            @Override
            public void removeLayoutComponent(java.awt.Component comp) {
            }

            @Override
            public java.awt.Dimension preferredLayoutSize(java.awt.Container parent) {
                return new java.awt.Dimension(800, 500);
            }

            @Override
            public java.awt.Dimension minimumLayoutSize(java.awt.Container parent) {
                return new java.awt.Dimension(800, 500);
            }

            @Override
            public void layoutContainer(java.awt.Container parent) {

                int frameWidth = parent.getWidth();
                int frameHeight = parent.getHeight();

                int panelWidth = 800;
                int panelHeight = 500;

                int x = (frameWidth - panelWidth) / 2;
                int y = (frameHeight - panelHeight) / 2;

                if (jPanel1 != null) {
                    jPanel1.setBounds(x, y, panelWidth, panelHeight);
                }
            }
        });

        this.getContentPane().revalidate();
        this.getContentPane().repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelKiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelKanan = new javax.swing.JPanel();
        LoginLogo = new javax.swing.JLabel();
        PasswordFont = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        UsernameFont = new javax.swing.JLabel();
        usernamekolom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        PanelKiri.setBackground(new java.awt.Color(0, 0, 0));
        PanelKiri.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Kiri.png"))); // NOI18N
        jLabel1.setText("my4");

        javax.swing.GroupLayout PanelKiriLayout = new javax.swing.GroupLayout(PanelKiri);
        PanelKiri.setLayout(PanelKiriLayout);
        PanelKiriLayout.setHorizontalGroup(
            PanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKiriLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelKiriLayout.setVerticalGroup(
            PanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKiriLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(PanelKiri);
        PanelKiri.setBounds(0, 0, 400, 500);

        PanelKanan.setBackground(new java.awt.Color(194, 148, 233));
        PanelKanan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/LoginFont1.png"))); // NOI18N
        PanelKanan.add(LoginLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 21, -1, 166));

        PasswordFont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/PasswordFont.png"))); // NOI18N
        PanelKanan.add(PasswordFont, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 160, 35));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        PanelKanan.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 305, 330, 48));

        UsernameFont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/UsernameFont1.png"))); // NOI18N
        UsernameFont.setText("Username :");
        PanelKanan.add(UsernameFont, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 175, 180, 35));

        usernamekolom.setBackground(new java.awt.Color(255, 255, 255));
        usernamekolom.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        usernamekolom.setForeground(new java.awt.Color(0, 0, 0));
        PanelKanan.add(usernamekolom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 330, 48));

        jButton1.setBackground(new java.awt.Color(194, 148, 233));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ButtonLogin.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        PanelKanan.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jPanel1.add(PanelKanan);
        PanelKanan.setBounds(400, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String usernameInput = usernamekolom.getText().trim();

        // PEMBERSIHAN MUTLAK: Ambil password dan langsung potong spasi liar di ujung teks
        String passwordInput = new String(jPasswordField1.getPassword()).trim();

        // Cek jika kolom kosong atau user masih menyisakan teks placeholder bawaan UI
        if (usernameInput.isEmpty() || passwordInput.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Username dan Password tidak boleh kosong!",
                    "Peringatan",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 1. Inisialisasi DAO untuk model Karyawan
            com.mycompany.transylvaniahotel.dao.BaseDAO<com.mycompany.transylvaniahotel.model.Karyawan> karyawanDAO
                    = new com.mycompany.transylvaniahotel.dao.GenericDAO<>("karyawan", com.mycompany.transylvaniahotel.model.Karyawan.class);

            // 2. Ambil data akun berdasarkan username inputan
            com.mycompany.transylvaniahotel.model.Karyawan akunKaryawan = karyawanDAO.getById("username", usernameInput);

            if (akunKaryawan != null) {

                // =========================================================================
                // CODE CEK INTEGRITAS DATA MONGODB
                // =========================================================================
                System.out.println("====== CEK DATA DARI MONGODB ======");
                System.out.println("Username dari Mongo : " + akunKaryawan.getUsername());
                System.out.println("Password dari Mongo : " + akunKaryawan.getPassword());
                System.out.println("Nama dari Mongo     : " + akunKaryawan.getNamaKaryawan());
                System.out.println("===================================");
                // =========================================================================

                // =========================================================================
                // SPRINT 3 INTEGRATION: KRIPTOGRAFI HASHING SHA-256
                // Ubah password plaintext dari form input menjadi format SHA-256 Hex murni
                // =========================================================================
                java.security.MessageDigest md = java.security.MessageDigest.getInstance("SHA-256");
                byte[] hashBytes = md.digest(passwordInput.getBytes());
                StringBuilder hexString = new StringBuilder();
                for (byte b : hashBytes) {
                    String hex = Integer.toHexString(0xff & b);
                    if (hex.length() == 1) {
                        hexString.append('0');
                    }
                    hexString.append(hex);
                }
                String hashedPasswordInput = hexString.toString();

                // =========================================================================
// KODE DEBUG SAKTI - CEK INTEGRITAS DATA
// =========================================================================
                System.out.println("\n=== DATA YANG DIBACA JAVA CHAT ===");
                System.out.println("Username Input       : '" + usernameInput + "'");
                System.out.println("Password Input (Asli): '" + passwordInput + "'");
                System.out.println("Hasil Hash Java      : " + hashedPasswordInput);
                System.out.println("Password dari Mongo  : " + (akunKaryawan != null ? akunKaryawan.getPassword() : "AKUN NULL"));
                System.out.println("===================================\n");
// =========================================================================
                // =========================================================================

                // 3. Bandingkan password hasil hash inputan dengan password hash di database
                // Ditambahkan .trim() ganda untuk menjamin tidak ada spasi hantu dari database
                if (akunKaryawan.getPassword().trim().equals(hashedPasswordInput.trim())) {

                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Login Berhasil!\nSelamat Datang, " + akunKaryawan.getNamaKaryawan() + " [" + akunKaryawan.getJabatan() + "]",
                            "Akses Berhasil",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);

                    // Tutup halaman login
                    this.dispose();

                    java.awt.EventQueue.invokeLater(() -> {
                        Dashboard dashboard = new Dashboard();
                        dashboard.setVisible(true);
                    });

                } else {
                    // Jika password hash tidak cocok
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Password yang Anda masukkan salah!",
                            "Login Gagal",
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                    jPasswordField1.setText("");
                    jPasswordField1.requestFocus();
                }
            } else {
                // Jika username tidak ada di koleksi MongoDB
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Username tidak terdaftar di sistem hotel!",
                        "Login Gagal",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                usernamekolom.setText("");
                jPasswordField1.setText("");
                usernamekolom.requestFocus();
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Gagal terhubung ke database MongoDB!\nPastikan MongoDB Compass atau Service aktif.\nError: " + e.getMessage(),
                    "Database Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained

    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost

    }//GEN-LAST:event_jPasswordField1FocusLost

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                logger.log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginLogo;
    private javax.swing.JPanel PanelKanan;
    private javax.swing.JPanel PanelKiri;
    private javax.swing.JLabel PasswordFont;
    private javax.swing.JLabel UsernameFont;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField usernamekolom;
    // End of variables declaration//GEN-END:variables
}
