package com.mycompany.transylvaniahotel.gui;

/**
 *
 * @author alfathrev
 */
import com.mycompany.transylvaniahotel.dao.BaseDAO;
import com.mycompany.transylvaniahotel.dao.GenericDAO;
import com.mycompany.transylvaniahotel.model.Karyawan;

public class Login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        // Membuat frame aplikasi otomatis muncul di tengah monitor saat pertama kali dibuka
        this.setLocationRelativeTo(null);

        // Menggunakan Layout Manager pada Content Pane agar posisi jPanel1 DIKUNCI selalu di tengah
        this.getContentPane().setLayout(new java.awt.LayoutManager() {
            @Override
            public void addLayoutComponent(String name, java.awt.Component comp) {
            }

            @Override
            public void removeLayoutComponent(java.awt.Component comp) {
            }

            @Override
            public java.awt.Dimension preferredLayoutSize(java.awt.Container parent) {
                return new java.awt.Dimension(800, 500);
            }

            @Override
            public java.awt.Dimension minimumLayoutSize(java.awt.Container parent) {
                return new java.awt.Dimension(800, 500);
            }

            @Override
            public void layoutContainer(java.awt.Container parent) {
                // Ambil ukuran area JFrame terbaru
                int frameWidth = parent.getWidth();
                int frameHeight = parent.getHeight();

                // Ukuran konstan panel login kamu
                int panelWidth = 800;
                int panelHeight = 500;

                // Hitung koordinat tengah
                int x = (frameWidth - panelWidth) / 2;
                int y = (frameHeight - panelHeight) / 2;

                // Paksa jPanel1 menempati area tengah, tidak peduli pop-up dibuka/tutup
                if (jPanel1 != null) {
                    jPanel1.setBounds(x, y, panelWidth, panelHeight);
                }
            }
        });

        // Bersihkan area dan gambar ulang layout baru
        this.getContentPane().revalidate();
        this.getContentPane().repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelKiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelKanan = new javax.swing.JPanel();
        LoginLogo = new javax.swing.JLabel();
        PasswordFont = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        UsernameFont = new javax.swing.JLabel();
        usernamekolom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        PanelKiri.setBackground(new java.awt.Color(0, 0, 0));
        PanelKiri.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Kiri.png"))); // NOI18N
        jLabel1.setText("my4");

        javax.swing.GroupLayout PanelKiriLayout = new javax.swing.GroupLayout(PanelKiri);
        PanelKiri.setLayout(PanelKiriLayout);
        PanelKiriLayout.setHorizontalGroup(
            PanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKiriLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelKiriLayout.setVerticalGroup(
            PanelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKiriLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(PanelKiri);
        PanelKiri.setBounds(0, 0, 400, 500);

        PanelKanan.setBackground(new java.awt.Color(194, 148, 233));
        PanelKanan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/LoginFont1.png"))); // NOI18N
        PanelKanan.add(LoginLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 21, -1, 166));

        PasswordFont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/PasswordFont.png"))); // NOI18N
        PanelKanan.add(PasswordFont, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 160, 35));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setText("jPasswordField1");
        PanelKanan.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 305, 330, 48));

        UsernameFont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/UsernameFont1.png"))); // NOI18N
        UsernameFont.setText("Username :");
        PanelKanan.add(UsernameFont, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 175, 180, 35));

        usernamekolom.setBackground(new java.awt.Color(255, 255, 255));
        usernamekolom.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        usernamekolom.setForeground(new java.awt.Color(0, 0, 0));
        PanelKanan.add(usernamekolom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 330, 48));

        jButton1.setBackground(new java.awt.Color(194, 148, 233));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ButtonLogin.png"))); // NOI18N
        jButton1.addActionListener(this::jButton1ActionPerformed);
        PanelKanan.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jPanel1.add(PanelKanan);
        PanelKanan.setBounds(400, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Ambil teks input dari field Username dan Password
        // .trim() digunakan untuk menghapus spasi tidak sengaja di awal/akhir input
        String usernameInput = usernamekolom.getText().trim();
        String passwordInput = new String(jPasswordField1.getPassword()); // Mengubah char[] password ke String

        // 2. Validasi awal: cegah proses jika ada field yang masih kosong
        if (usernameInput.isEmpty() || passwordInput.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Username dan Password tidak boleh kosong!",
                    "Peringatan",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 3. Inisialisasi GenericDAO untuk model Karyawan dan koleksi bernama "karyawan"
            com.mycompany.transylvaniahotel.dao.BaseDAO<com.mycompany.transylvaniahotel.model.Karyawan> karyawanDAO
                    = new com.mycompany.transylvaniahotel.dao.GenericDAO<>("karyawan", com.mycompany.transylvaniahotel.model.Karyawan.class);

            // 4. Cari data karyawan berdasarkan field "username" yang diketik user
            // Fungsi getById() di GenericDAO milikmu akan me-return objek Karyawan jika ketemu, atau null jika tidak ada
            com.mycompany.transylvaniahotel.model.Karyawan akunKaryawan = karyawanDAO.getById("username", usernameInput);

            // 5. Verifikasi akun hasil query dari MongoDB
            if (akunKaryawan != null) {
                // Jika username ada, validasi apakah password-nya cocok menggunakan .getPassword() dari entity Karyawan
                if (akunKaryawan.getPassword().equals(passwordInput)) {

                    // === LOGIN SUKSES ===
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Login Berhasil!\nSelamat Datang, " + akunKaryawan.getNamaKaryawan() + " [" + akunKaryawan.getJabatan() + "]",
                            "Akses Berhasil",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);

                    // Menutup frame login saat ini karena login sudah berhasil
                    this.dispose();

                    // Catatan: Jika nanti kamu sudah membuat class Dashboard di package gui, 
                    // tinggal aktifkan dua baris di bawah ini untuk berpindah halaman:
                    // com.mycompany.transylvaniahotel.gui.DashboardUtama dashboard = new com.mycompany.transylvaniahotel.gui.DashboardUtama();
                    // dashboard.setVisible(true);
                } else {
                    // Jika username ditemukan tetapi password-nya salah
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Password yang Anda masukkan salah!",
                            "Login Gagal",
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                    jPasswordField1.setText(""); // Kosongkan kolom password
                    jPasswordField1.requestFocus(); // Taruh kursor kembali ke kolom password
                }
            } else {
                // Jika username tidak ditemukan sama sekali di koleksi MongoDB
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Username tidak terdaftar di sistem hotel!",
                        "Login Gagal",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                usernamekolom.setText("");
                jPasswordField1.setText("");
                usernamekolom.requestFocus(); // Taruh kursor kembali ke kolom username
            }

        } catch (Exception e) {
            // Antisipasi jika service database MongoDB lokal (atau mongod) belum dijalankan di PC
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Gagal terhubung ke database MongoDB!\nPastikan MongoDB Compass atau Service aktif.\nError: " + e.getMessage(),
                    "Database Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginLogo;
    private javax.swing.JPanel PanelKanan;
    private javax.swing.JPanel PanelKiri;
    private javax.swing.JLabel PasswordFont;
    private javax.swing.JLabel UsernameFont;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField usernamekolom;
    // End of variables declaration//GEN-END:variables
}
